import { sanitizeText } from "@/lib/validation";

export const bool=(v:unknown)=>v===true||v===1||v==="1"||v==="true";
export const num=(v:unknown)=>Math.max(0,Math.min(1_000_000,Number(v)||0));
export function url(v:unknown, required=false){const s=String(v||"").trim();if(!s&&required)throw new Error("A URL is required");if(s){const u=new URL(s,"https://local.invalid");if(!["http:","https:"].includes(u.protocol))throw new Error("Only http(s) URLs are allowed");if(s.startsWith("/"))return s;}return s}
export function newsInput(b:Record<string,unknown>){const title=sanitizeText(String(b.title||""),180);if(!title)throw new Error("Post title is required");const raw=String(b.publishDate||new Date().toISOString());if(Number.isNaN(Date.parse(raw)))throw new Error("Invalid publish date");return{title,body:sanitizeText(String(b.body||""),5000),imageUrl:url(b.imageUrl),youtubeUrl:url(b.youtubeUrl),externalUrl:url(b.externalUrl),topic:sanitizeText(String(b.topic||""),80),publishDate:new Date(raw).toISOString(),enabled:bool(b.enabled),pinned:bool(b.pinned),orderNumber:num(b.orderNumber)}}
export function websiteInput(b:Record<string,unknown>){return{name:sanitizeText(String(b.name||""),80),url:url(b.url),icon:sanitizeText(String(b.icon||"🌐"),30),enabled:bool(b.enabled),orderNumber:num(b.orderNumber)}}
function absoluteWebUrl(v:unknown){const s=String(v||"").trim();if(!s)return"";let parsed:URL;try{parsed=new URL(s)}catch{throw new Error("Enter a complete URL beginning with http:// or https://")}if(parsed.protocol!=="http:"&&parsed.protocol!=="https:")throw new Error("Only http:// or https:// URLs are allowed");return parsed.toString()}
export function platformInput(b:Record<string,unknown>){const premiumAppsUrl=absoluteWebUrl(b.premiumAppsUrl);const youtubeExternalUrl=absoluteWebUrl(b.youtubeExternalUrl);const premiumAppsEnabled=bool(b.premiumAppsEnabled);const youtubeExternalEnabled=bool(b.youtubeExternalEnabled);if(premiumAppsEnabled&&!premiumAppsUrl)throw new Error("Premium Apps URL is required when enabled");if(youtubeExternalEnabled&&!youtubeExternalUrl)throw new Error("YouTube URL is required when enabled");return{telegramEnabled:bool(b.telegramEnabled),telegramUrl:url(b.telegramUrl),telegramText:sanitizeText(String(b.telegramText||""),120),telegramIcon:sanitizeText(String(b.telegramIcon||"✈️"),30),telegramPosition:b.telegramPosition==="bottom-right"?"bottom-right" as const:"bottom-left" as const,telegramAnimation:bool(b.telegramAnimation),telegramDelay:Math.min(60000,num(b.telegramDelay)),installBannerEnabled:bool(b.installBannerEnabled),installTitle:sanitizeText(String(b.installTitle||""),80),installText:sanitizeText(String(b.installText||""),160),apkUrl:url(b.apkUrl,true),webInstallEnabled:bool(b.webInstallEnabled),premiumAppsUrl,premiumAppsEnabled,youtubeExternalUrl,youtubeExternalEnabled}}
